// Stable error codes. Frontend mirrors this list in frontend/src/lib/errorCodes.ts.
// Adding a code: extend both files in lockstep + add messages in i18n.ts +
// add translations in frontend/src/i18n/locales/{en-CA,fr-CA}/errors.json.

export const ERROR_CODES = [
  // Generic
  "INTERNAL_ERROR",
  "VALIDATION_ERROR",
  // Auth
  "AUTH_REQUIRED",
  "AUTH_INVALID_TOKEN",
  "AUTH_INVALID_CREDENTIALS",
  "AUTH_EMAIL_IN_USE",
  "AUTH_REFRESH_TOKEN_MISSING",
  "AUTH_REFRESH_TOKEN_INVALID",
  "AUTH_REFRESH_TOKEN_EXPIRED",
  "AUTH_CSRF_FAILED",
  "AUTH_FORBIDDEN_ROLE",
  "AUTH_RATE_LIMITED",
  // User
  "USER_NOT_FOUND",
  "USER_SUPERVISOR_INVALID_ROLE",
  "SUPERVISOR_NOT_FOUND",
  // Account
  "ACCOUNT_NOT_FOUND",
  "ACCOUNT_NUMBER_DUPLICATE",
  "ACCOUNT_NOT_SUPERVISOR_ROLE",
  "ACCOUNT_OWN_ONLY",
  // Request
  "REQUEST_NOT_FOUND",
  "REQUEST_ACCESS_DENIED",
  "REQUEST_OWNER_ONLY_EDIT",
  "REQUEST_WRONG_STATUS_EDIT",
  "REQUEST_WRONG_STATUS_DELETE",
  "REQUEST_WRONG_STATUS_SUBMIT",
  "REQUEST_WRONG_STATUS_REVISE",
  "TRAVEL_DETAILS_REQUIRED",
  "TRAVEL_DESTINATION_REQUIRED",
  "TRAVEL_PURPOSE_REQUIRED",
  "LINKED_ADVANCE_MISSING",
  "LINKED_ADVANCE_NOT_OWNED",
  "LINKED_ADVANCE_WRONG_TYPE",
  "LINKED_ADVANCE_NOT_PAID",
  // Approval
  "APPROVAL_WRONG_STATUS",
  "APPROVAL_WRONG_SUPERVISOR",
  "APPROVAL_ACCOUNT_NOT_FOUND",
  "APPROVAL_ACCOUNT_INACTIVE",
  "APPROVAL_ALREADY_APPROVED",
  "APPROVAL_ITEMS_NOT_CLASSIFIED",
  "APPROVAL_PAID_WRONG_STATUS",
  // Classification
  "CLASSIFICATION_WRONG_STATUS",
  "CLASSIFICATION_ITEM_NOT_FOUND",
  // Document
  "DOCUMENT_NOT_FOUND",
  "DOCUMENT_OWNER_ONLY_UPLOAD",
  "DOCUMENT_OWNER_ONLY_DELETE",
  "DOCUMENT_REQUEST_WRONG_STATUS",
  "DOCUMENT_FILE_FIELD_REQUIRED",
  "DOCUMENT_FILE_TOO_LARGE",
  "DOCUMENT_TYPE_NOT_ALLOWED",
  "DOCUMENT_ITEM_MISMATCH",
] as const;

export type ErrorCode = typeof ERROR_CODES[number];

export const VALIDATION_ISSUE_CODES = [
  "VALIDATION_REQUIRED",
  "VALIDATION_TYPE",
  "VALIDATION_MIN",
  "VALIDATION_MAX",
  "VALIDATION_EMAIL",
  "VALIDATION_ENUM",
  "VALIDATION_INVALID",
] as const;

export type ValidationIssueCode = typeof VALIDATION_ISSUE_CODES[number];
