/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthReviewRouteRouteImport } from './routes/_auth/review/route'
import { Route as AuthFinanceRouteRouteImport } from './routes/_auth/finance/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthReviewIndexRouteImport } from './routes/_auth/review/index'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthFinanceIndexRouteImport } from './routes/_auth/finance/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthReviewRequestIdRouteImport } from './routes/_auth/review/$requestId'
import { Route as AuthFinanceRequestIdRouteImport } from './routes/_auth/finance/$requestId'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthDashboardRequestsIndexRouteImport } from './routes/_auth/dashboard/requests/index'
import { Route as AuthDashboardRequestsNewRouteImport } from './routes/_auth/dashboard/requests/new'
import { Route as AuthDashboardRequestsRequestIdRouteImport } from './routes/_auth/dashboard/requests/$requestId'
import { Route as AuthDashboardRequestsNewIndexRouteImport } from './routes/_auth/dashboard/requests/new.index'
import { Route as AuthDashboardRequestsRequestIdIndexRouteImport } from './routes/_auth/dashboard/requests/$requestId.index'
import { Route as AuthDashboardRequestsNewTravelReimbursementRouteImport } from './routes/_auth/dashboard/requests/new.travel-reimbursement'
import { Route as AuthDashboardRequestsNewTravelAdvanceRouteImport } from './routes/_auth/dashboard/requests/new.travel-advance'
import { Route as AuthDashboardRequestsNewReimbursementRouteImport } from './routes/_auth/dashboard/requests/new.reimbursement'
import { Route as AuthDashboardRequestsRequestIdEditRouteImport } from './routes/_auth/dashboard/requests/$requestId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReviewRouteRoute = AuthReviewRouteRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFinanceRouteRoute = AuthFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReviewIndexRoute = AuthReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthReviewRouteRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFinanceIndexRoute = AuthFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFinanceRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReviewRequestIdRoute = AuthReviewRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => AuthReviewRouteRoute,
} as any)
const AuthFinanceRequestIdRoute = AuthFinanceRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => AuthFinanceRouteRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthDashboardRequestsIndexRoute =
  AuthDashboardRequestsIndexRouteImport.update({
    id: '/dashboard/requests/',
    path: '/dashboard/requests/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthDashboardRequestsNewRoute =
  AuthDashboardRequestsNewRouteImport.update({
    id: '/dashboard/requests/new',
    path: '/dashboard/requests/new',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthDashboardRequestsRequestIdRoute =
  AuthDashboardRequestsRequestIdRouteImport.update({
    id: '/dashboard/requests/$requestId',
    path: '/dashboard/requests/$requestId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthDashboardRequestsNewIndexRoute =
  AuthDashboardRequestsNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardRequestsNewRoute,
  } as any)
const AuthDashboardRequestsRequestIdIndexRoute =
  AuthDashboardRequestsRequestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardRequestsRequestIdRoute,
  } as any)
const AuthDashboardRequestsNewTravelReimbursementRoute =
  AuthDashboardRequestsNewTravelReimbursementRouteImport.update({
    id: '/travel-reimbursement',
    path: '/travel-reimbursement',
    getParentRoute: () => AuthDashboardRequestsNewRoute,
  } as any)
const AuthDashboardRequestsNewTravelAdvanceRoute =
  AuthDashboardRequestsNewTravelAdvanceRouteImport.update({
    id: '/travel-advance',
    path: '/travel-advance',
    getParentRoute: () => AuthDashboardRequestsNewRoute,
  } as any)
const AuthDashboardRequestsNewReimbursementRoute =
  AuthDashboardRequestsNewReimbursementRouteImport.update({
    id: '/reimbursement',
    path: '/reimbursement',
    getParentRoute: () => AuthDashboardRequestsNewRoute,
  } as any)
const AuthDashboardRequestsRequestIdEditRoute =
  AuthDashboardRequestsRequestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthDashboardRequestsRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/finance': typeof AuthFinanceRouteRouteWithChildren
  '/review': typeof AuthReviewRouteRouteWithChildren
  '/admin/users': typeof AuthAdminUsersRoute
  '/finance/$requestId': typeof AuthFinanceRequestIdRoute
  '/review/$requestId': typeof AuthReviewRequestIdRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/finance/': typeof AuthFinanceIndexRoute
  '/profile/': typeof AuthProfileIndexRoute
  '/review/': typeof AuthReviewIndexRoute
  '/dashboard/requests/$requestId': typeof AuthDashboardRequestsRequestIdRouteWithChildren
  '/dashboard/requests/new': typeof AuthDashboardRequestsNewRouteWithChildren
  '/dashboard/requests/': typeof AuthDashboardRequestsIndexRoute
  '/dashboard/requests/$requestId/edit': typeof AuthDashboardRequestsRequestIdEditRoute
  '/dashboard/requests/new/reimbursement': typeof AuthDashboardRequestsNewReimbursementRoute
  '/dashboard/requests/new/travel-advance': typeof AuthDashboardRequestsNewTravelAdvanceRoute
  '/dashboard/requests/new/travel-reimbursement': typeof AuthDashboardRequestsNewTravelReimbursementRoute
  '/dashboard/requests/$requestId/': typeof AuthDashboardRequestsRequestIdIndexRoute
  '/dashboard/requests/new/': typeof AuthDashboardRequestsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/admin/users': typeof AuthAdminUsersRoute
  '/finance/$requestId': typeof AuthFinanceRequestIdRoute
  '/review/$requestId': typeof AuthReviewRequestIdRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/finance': typeof AuthFinanceIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/review': typeof AuthReviewIndexRoute
  '/dashboard/requests': typeof AuthDashboardRequestsIndexRoute
  '/dashboard/requests/$requestId/edit': typeof AuthDashboardRequestsRequestIdEditRoute
  '/dashboard/requests/new/reimbursement': typeof AuthDashboardRequestsNewReimbursementRoute
  '/dashboard/requests/new/travel-advance': typeof AuthDashboardRequestsNewTravelAdvanceRoute
  '/dashboard/requests/new/travel-reimbursement': typeof AuthDashboardRequestsNewTravelReimbursementRoute
  '/dashboard/requests/$requestId': typeof AuthDashboardRequestsRequestIdIndexRoute
  '/dashboard/requests/new': typeof AuthDashboardRequestsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/finance': typeof AuthFinanceRouteRouteWithChildren
  '/_auth/review': typeof AuthReviewRouteRouteWithChildren
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/finance/$requestId': typeof AuthFinanceRequestIdRoute
  '/_auth/review/$requestId': typeof AuthReviewRequestIdRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/finance/': typeof AuthFinanceIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_auth/review/': typeof AuthReviewIndexRoute
  '/_auth/dashboard/requests/$requestId': typeof AuthDashboardRequestsRequestIdRouteWithChildren
  '/_auth/dashboard/requests/new': typeof AuthDashboardRequestsNewRouteWithChildren
  '/_auth/dashboard/requests/': typeof AuthDashboardRequestsIndexRoute
  '/_auth/dashboard/requests/$requestId/edit': typeof AuthDashboardRequestsRequestIdEditRoute
  '/_auth/dashboard/requests/new/reimbursement': typeof AuthDashboardRequestsNewReimbursementRoute
  '/_auth/dashboard/requests/new/travel-advance': typeof AuthDashboardRequestsNewTravelAdvanceRoute
  '/_auth/dashboard/requests/new/travel-reimbursement': typeof AuthDashboardRequestsNewTravelReimbursementRoute
  '/_auth/dashboard/requests/$requestId/': typeof AuthDashboardRequestsRequestIdIndexRoute
  '/_auth/dashboard/requests/new/': typeof AuthDashboardRequestsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/finance'
    | '/review'
    | '/admin/users'
    | '/finance/$requestId'
    | '/review/$requestId'
    | '/dashboard/'
    | '/finance/'
    | '/profile/'
    | '/review/'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests/new'
    | '/dashboard/requests/'
    | '/dashboard/requests/$requestId/edit'
    | '/dashboard/requests/new/reimbursement'
    | '/dashboard/requests/new/travel-advance'
    | '/dashboard/requests/new/travel-reimbursement'
    | '/dashboard/requests/$requestId/'
    | '/dashboard/requests/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/users'
    | '/finance/$requestId'
    | '/review/$requestId'
    | '/dashboard'
    | '/finance'
    | '/profile'
    | '/review'
    | '/dashboard/requests'
    | '/dashboard/requests/$requestId/edit'
    | '/dashboard/requests/new/reimbursement'
    | '/dashboard/requests/new/travel-advance'
    | '/dashboard/requests/new/travel-reimbursement'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/finance'
    | '/_auth/review'
    | '/_auth/admin/users'
    | '/_auth/finance/$requestId'
    | '/_auth/review/$requestId'
    | '/_auth/dashboard/'
    | '/_auth/finance/'
    | '/_auth/profile/'
    | '/_auth/review/'
    | '/_auth/dashboard/requests/$requestId'
    | '/_auth/dashboard/requests/new'
    | '/_auth/dashboard/requests/'
    | '/_auth/dashboard/requests/$requestId/edit'
    | '/_auth/dashboard/requests/new/reimbursement'
    | '/_auth/dashboard/requests/new/travel-advance'
    | '/_auth/dashboard/requests/new/travel-reimbursement'
    | '/_auth/dashboard/requests/$requestId/'
    | '/_auth/dashboard/requests/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/review': {
      id: '/_auth/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthReviewRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/finance': {
      id: '/_auth/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthFinanceRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/review/': {
      id: '/_auth/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof AuthReviewIndexRouteImport
      parentRoute: typeof AuthReviewRouteRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/finance/': {
      id: '/_auth/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthFinanceIndexRouteImport
      parentRoute: typeof AuthFinanceRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/review/$requestId': {
      id: '/_auth/review/$requestId'
      path: '/$requestId'
      fullPath: '/review/$requestId'
      preLoaderRoute: typeof AuthReviewRequestIdRouteImport
      parentRoute: typeof AuthReviewRouteRoute
    }
    '/_auth/finance/$requestId': {
      id: '/_auth/finance/$requestId'
      path: '/$requestId'
      fullPath: '/finance/$requestId'
      preLoaderRoute: typeof AuthFinanceRequestIdRouteImport
      parentRoute: typeof AuthFinanceRouteRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/dashboard/requests/': {
      id: '/_auth/dashboard/requests/'
      path: '/dashboard/requests'
      fullPath: '/dashboard/requests/'
      preLoaderRoute: typeof AuthDashboardRequestsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/requests/new': {
      id: '/_auth/dashboard/requests/new'
      path: '/dashboard/requests/new'
      fullPath: '/dashboard/requests/new'
      preLoaderRoute: typeof AuthDashboardRequestsNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/requests/$requestId': {
      id: '/_auth/dashboard/requests/$requestId'
      path: '/dashboard/requests/$requestId'
      fullPath: '/dashboard/requests/$requestId'
      preLoaderRoute: typeof AuthDashboardRequestsRequestIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/requests/new/': {
      id: '/_auth/dashboard/requests/new/'
      path: '/'
      fullPath: '/dashboard/requests/new/'
      preLoaderRoute: typeof AuthDashboardRequestsNewIndexRouteImport
      parentRoute: typeof AuthDashboardRequestsNewRoute
    }
    '/_auth/dashboard/requests/$requestId/': {
      id: '/_auth/dashboard/requests/$requestId/'
      path: '/'
      fullPath: '/dashboard/requests/$requestId/'
      preLoaderRoute: typeof AuthDashboardRequestsRequestIdIndexRouteImport
      parentRoute: typeof AuthDashboardRequestsRequestIdRoute
    }
    '/_auth/dashboard/requests/new/travel-reimbursement': {
      id: '/_auth/dashboard/requests/new/travel-reimbursement'
      path: '/travel-reimbursement'
      fullPath: '/dashboard/requests/new/travel-reimbursement'
      preLoaderRoute: typeof AuthDashboardRequestsNewTravelReimbursementRouteImport
      parentRoute: typeof AuthDashboardRequestsNewRoute
    }
    '/_auth/dashboard/requests/new/travel-advance': {
      id: '/_auth/dashboard/requests/new/travel-advance'
      path: '/travel-advance'
      fullPath: '/dashboard/requests/new/travel-advance'
      preLoaderRoute: typeof AuthDashboardRequestsNewTravelAdvanceRouteImport
      parentRoute: typeof AuthDashboardRequestsNewRoute
    }
    '/_auth/dashboard/requests/new/reimbursement': {
      id: '/_auth/dashboard/requests/new/reimbursement'
      path: '/reimbursement'
      fullPath: '/dashboard/requests/new/reimbursement'
      preLoaderRoute: typeof AuthDashboardRequestsNewReimbursementRouteImport
      parentRoute: typeof AuthDashboardRequestsNewRoute
    }
    '/_auth/dashboard/requests/$requestId/edit': {
      id: '/_auth/dashboard/requests/$requestId/edit'
      path: '/edit'
      fullPath: '/dashboard/requests/$requestId/edit'
      preLoaderRoute: typeof AuthDashboardRequestsRequestIdEditRouteImport
      parentRoute: typeof AuthDashboardRequestsRequestIdRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminUsersRoute: AuthAdminUsersRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthFinanceRouteRouteChildren {
  AuthFinanceRequestIdRoute: typeof AuthFinanceRequestIdRoute
  AuthFinanceIndexRoute: typeof AuthFinanceIndexRoute
}

const AuthFinanceRouteRouteChildren: AuthFinanceRouteRouteChildren = {
  AuthFinanceRequestIdRoute: AuthFinanceRequestIdRoute,
  AuthFinanceIndexRoute: AuthFinanceIndexRoute,
}

const AuthFinanceRouteRouteWithChildren =
  AuthFinanceRouteRoute._addFileChildren(AuthFinanceRouteRouteChildren)

interface AuthReviewRouteRouteChildren {
  AuthReviewRequestIdRoute: typeof AuthReviewRequestIdRoute
  AuthReviewIndexRoute: typeof AuthReviewIndexRoute
}

const AuthReviewRouteRouteChildren: AuthReviewRouteRouteChildren = {
  AuthReviewRequestIdRoute: AuthReviewRequestIdRoute,
  AuthReviewIndexRoute: AuthReviewIndexRoute,
}

const AuthReviewRouteRouteWithChildren = AuthReviewRouteRoute._addFileChildren(
  AuthReviewRouteRouteChildren,
)

interface AuthDashboardRequestsRequestIdRouteChildren {
  AuthDashboardRequestsRequestIdEditRoute: typeof AuthDashboardRequestsRequestIdEditRoute
  AuthDashboardRequestsRequestIdIndexRoute: typeof AuthDashboardRequestsRequestIdIndexRoute
}

const AuthDashboardRequestsRequestIdRouteChildren: AuthDashboardRequestsRequestIdRouteChildren =
  {
    AuthDashboardRequestsRequestIdEditRoute:
      AuthDashboardRequestsRequestIdEditRoute,
    AuthDashboardRequestsRequestIdIndexRoute:
      AuthDashboardRequestsRequestIdIndexRoute,
  }

const AuthDashboardRequestsRequestIdRouteWithChildren =
  AuthDashboardRequestsRequestIdRoute._addFileChildren(
    AuthDashboardRequestsRequestIdRouteChildren,
  )

interface AuthDashboardRequestsNewRouteChildren {
  AuthDashboardRequestsNewReimbursementRoute: typeof AuthDashboardRequestsNewReimbursementRoute
  AuthDashboardRequestsNewTravelAdvanceRoute: typeof AuthDashboardRequestsNewTravelAdvanceRoute
  AuthDashboardRequestsNewTravelReimbursementRoute: typeof AuthDashboardRequestsNewTravelReimbursementRoute
  AuthDashboardRequestsNewIndexRoute: typeof AuthDashboardRequestsNewIndexRoute
}

const AuthDashboardRequestsNewRouteChildren: AuthDashboardRequestsNewRouteChildren =
  {
    AuthDashboardRequestsNewReimbursementRoute:
      AuthDashboardRequestsNewReimbursementRoute,
    AuthDashboardRequestsNewTravelAdvanceRoute:
      AuthDashboardRequestsNewTravelAdvanceRoute,
    AuthDashboardRequestsNewTravelReimbursementRoute:
      AuthDashboardRequestsNewTravelReimbursementRoute,
    AuthDashboardRequestsNewIndexRoute: AuthDashboardRequestsNewIndexRoute,
  }

const AuthDashboardRequestsNewRouteWithChildren =
  AuthDashboardRequestsNewRoute._addFileChildren(
    AuthDashboardRequestsNewRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthFinanceRouteRoute: typeof AuthFinanceRouteRouteWithChildren
  AuthReviewRouteRoute: typeof AuthReviewRouteRouteWithChildren
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthDashboardRequestsRequestIdRoute: typeof AuthDashboardRequestsRequestIdRouteWithChildren
  AuthDashboardRequestsNewRoute: typeof AuthDashboardRequestsNewRouteWithChildren
  AuthDashboardRequestsIndexRoute: typeof AuthDashboardRequestsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthFinanceRouteRoute: AuthFinanceRouteRouteWithChildren,
  AuthReviewRouteRoute: AuthReviewRouteRouteWithChildren,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthDashboardRequestsRequestIdRoute:
    AuthDashboardRequestsRequestIdRouteWithChildren,
  AuthDashboardRequestsNewRoute: AuthDashboardRequestsNewRouteWithChildren,
  AuthDashboardRequestsIndexRoute: AuthDashboardRequestsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
